### ISSUE TITLE
ironic_node_v1.openshift-master-0: cannot go from state 'deploy failed' to state 'manageable'"

### ISSUE THREAD

**Issue by rwsu** [openshift-metalkube/dev-scripts#284]
On commit 0fb6eb9f690fa0b9fd15ce6e74889e800c2da3e6 using nest virt running first step, "make".

```
level=debug msg="module.masters.ironic_node_v1.openshift-master-0: Still creating... (31m31s elapsed)"
level=debug msg="module.masters.ironic_node_v1.openshift-master-0: Still creating... (31m41s elapsed)"
level=error
level=error msg="Error: Error applying plan:"
level=error
level=error msg="1 error occurred:"
level=error msg="\t* module.masters.ironic_node_v1.openshift-master-0: 1 error occurred:"
level=error msg="\t* ironic_node_v1.openshift-master-0: cannot go from state 'deploy failed' to state 'manageable'"
level=error
level=error
level=error
level=error
level=error
level=error msg="Terraform does not automatically rollback in the face of errors."
level=error msg="Instead, your Terraform state file has been partially updated with"
level=error msg="any resources that successfully completed. Please address the error"
level=error msg="above and apply again to incrementally change your infrastructure."
level=error
level=error
level=fatal msg="failed to fetch Cluster: failed to generate asset \"Cluster\": failed to create cluster: failed to apply using Terraform"
make: *** [ocp_run] Error 1
```

**Comment by stbenjam** [comment]
How much memory do you have on your server?

**Comment by rwsu** [comment]
@stbenjam 32gb. I see I need at least 48gb. Is that the cause of the error?

**Comment by hardys** [comment]
I have been testing on a 32g box, but we did land a patch yesterday (#254) that increased the memory requirements from 6G to 8G per VM, I've not tested on that machine since that landed.

All we can see from the error as reported is that ironic failed, to debug we need to see why - you can interact directly with the ironic service as described here:

https://github.com/openshift-metalkube/dev-scripts#interacting-with-ironic-directly

If you use `openstack baremetal node show <node>` on the host you will hopefully get some clues as to what is failing.

You can also exec into the ironic container to check the logs if the CLI doesn't provide enough information.

**Comment by hardys** [comment]
Can you please confirm if this is still an issue @rwsu - as previously mentioned we'll need more info to help debug this, but last week we had a bunch of problems which should now be resolved, perhaps you can re-test and close this if things are working OK now?  Thanks!

**Comment by rwsu** [comment]
@hardys for future reference, with a nested VM, the install goes further and eventually times out waiting for:

````
level=debug msg="Still waiting for the cluster to initialize: Working towards 4.0.0-0.alpha-2019-04-08-195526: 92% complete"
level=fatal msg="failed to initialize the cluster: Working towards 4.0.0-0.alpha-2019-04-08-195526: 92% complete: timed out waiting for the condition"
````

I then gave up on nested and tried installing on baremetal with 32gb of ram. That was successful.

Closing this issue.
