### ISSUE TITLE
Manual execution of this line fails 

### ISSUE THREAD

**Issue by Stef1010** [openshift-metalkube/dev-scripts#356]
https://github.com/openshift-metalkube/dev-scripts/blob/ecf60de2ea62593bb1613c5ee1af2a888ed3d261/assets/files/etc/kubernetes/manifests/mdns-publisher.yaml#L54

[core@master-1 ~]$ ONE_CIDR="$(ip addr show to "$SUBNET_CIDR" | \
>                   grep -Po 'inet \K[\d.]+/[\d.]+' | \
>                   grep -v "${DNS_VIP}/$PREFIX" | \
>                   grep -v "${API_VIP}/$PREFIX" | \
>                   sort | xargs | cut -f1 -d' ')"
Error: any valid prefix is expected rather than "".

**Comment by karmab** [comment]
i think it fails because 
- you need to set all the variables from the previous lines
- one of the previous lines refer to DOMAIN variable which is to be set in clusterrc
you indicated in https://github.com/openshift-metalkube/dev-scripts/issues/355 that the clusterrc file was missing, so i suggest to focus on this particularly

**Comment by hardys** [comment]
As previously mentioned I think this bug is invalid, please reopen with more information if you think this is not the case.
